name: Patch

on:
  workflow_dispatch:

jobs:
  patch:
    runs-on: macos-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Check signature
        run: |
          pkgutil --check-signature RosettaUpdateAuto.pkg
          pkgutil --check-signature RosettaUpdateAuto.pkg | head -n 2 | tail -n 1 | grep -E '^\s+Status: signed Apple Software$' >/dev/null

      - name: Extract
        run: |
          pkgutil --expand-full RosettaUpdateAuto.pkg RosettaUpdateAuto.pkg-expanded
          cp RosettaUpdateAuto.pkg-expanded/RosettaUpdateAuto.pkg/Payload/Library/Apple/usr/libexec/oah/RosettaLinux/rosetta ./rosetta

      - name: Upload To Github Release
        uses: xresloader/upload-to-github-release@v1.3.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "rosetta" 
          tags: false
          draft: false
          overwrite: true
          verbose: true
          update_latest_release: false
          tag_name: "unpatched"
          

      - name: Patch
        run: |
          dd if=<(printf '\x1f\x20\x03\xd5') of='rosetta' bs=1 seek=170828 conv=notrunc
          dd if=<(printf '\x1f\x20\x03\xd5') of='rosetta' bs=1 seek=170856 conv=notrunc

          
      - name: Upload To Github Release
        uses: xresloader/upload-to-github-release@v1.3.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "rosetta" 
          tags: false
          draft: false
          overwrite: false
          verbose: true
          update_latest_release: false
          tag_name: "patched"
